import 'package:order_ticket/constants/path_location.dart';
import 'package:order_ticket/models/user_model.dart';

class UserRepository {
  static List<User> getUserData() {
    List<User> userData = [
      User(
        id: 1,
        name: "Amit Shrestha",
        time: "40 minutes ago",
        totalAmount: 2500,
        imageLocation: kUserImageLocation,
        email: "amitshrestha@gmail.com",
        phoneNumber: "9800000000",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 3,
        date: "21 Nov, 2020",
        paymentMethod: "Post Credit",
        dueAmount: 3500,
      ),
      User(
        id: 2,
        name: "Bhagyashree Thapa",
        time: "1 hour 40 minutes ago",
        totalAmount: 2100,
        imageLocation: kUserImageLocation,
        email: "bhagyashreethapa@gmail.com",
        phoneNumber: "9811111111",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 1,
        date: "21 Dec, 2020",
        paymentMethod: "Advance/Post Credit",
        dueAmount: 300,
      ),
      User(
        id: 3,
        name: "Yumi Gurung",
        time: "1:20 pm",
        totalAmount: 2500,
        imageLocation: kUserImageLocation,
        email: "yumigurung@gmail.com",
        phoneNumber: "9822222222",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 2,
        date: "21 Nov, 2021",
        paymentMethod: "Debit",
        dueAmount: 0,
      ),
      User(
        id: 4,
        name: "Kritikaa Thapa",
        time: "1:21 pm",
        totalAmount: 1121,
        imageLocation: kUserImageLocation,
        email: "kritikaathapa@gmail.com",
        phoneNumber: "9833333333",
        location: "Lamjung",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 1,
        date: "02 Jan, 2022",
        paymentMethod: "Post Credit",
        dueAmount: 0,
      ),
      User(
        id: 5,
        name: "Anmol Gurung",
        time: "1:34 pm",
        totalAmount: 2500,
        imageLocation: kUserImageLocation,
        email: "anmolgurung@gmail.com",
        phoneNumber: "9844444444",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 7,
        date: "21 Feb, 2021",
        paymentMethod: "Post Credit",
        dueAmount: 1390,
      ),
      User(
        id: 6,
        name: "Nrijala Shrestha",
        time: "3:11 pm",
        totalAmount: 2211,
        imageLocation: kUserImageLocation,
        email: "nrijalashrestha@gmail.com",
        phoneNumber: "9855555555",
        location: "Bharatpur",
        comment: "--",
        badge: 0.5,
        shoppingBasket: 1,
        date: "21 March, 2021",
        paymentMethod: "Post Credit",
        dueAmount: 35,
      ),
      User(
        id: 7,
        name: "Amit Shrestha",
        time: "3:12 pm",
        totalAmount: 3421,
        imageLocation: kUserImageLocation,
        email: "amitshrestha@gmail.com",
        phoneNumber: "9800000000",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 3,
        date: "21 Nov, 2020",
        paymentMethod: "Post Credit",
        dueAmount: 3500,
      ),
      User(
        id: 8,
        name: "Niraj Shrestha",
        time: "4:00 pm",
        totalAmount: 2500,
        imageLocation: kUserImageLocation,
        email: "nirajshrestha@gmail.com",
        phoneNumber: "9866666666",
        location: "Pokhara",
        comment: "--",
        badge: 0.0,
        shoppingBasket: 3,
        date: "21 Apr, 2021",
        paymentMethod: "Post Credit",
        dueAmount: 0,
      ),
    ];
    return userData;
  }
}
